:zap: Updating output basic_utilities.yaml and chocolatine.yml

diff --git a/.github/workflows/basic_utilities.yaml b/.github/workflows/basic_utilities.yaml
--- a/.github/workflows/basic_utilities.yaml
+++ b/.github/workflows/basic_utilities.yaml
@@ -59,27 +59,33 @@ jobs:
           cargo build && cp target/debug/ftest ./ftest
           cd ..
 
+      - name: Run ftests
+        run: |
+          ./ftest/ftest > ftest.log
+        continue-on-error: true
+
+      - name: Display error
+        if: ${{ failure() }}
+        run: |
+          ./ftest/ftest > ftest.log
+          IFS=$'\n'
+          STR1=""
+          STR2=""
+          for line in $(cat ftest.log | grep Failed --before-context=2); do
+            if [[ $line != *"Failed"* && $line == *"----"* ]]; then
+              STR1=$line
+            elif [[ $line != *"Failed"* && $line != *"----"* ]]; then
+              STR2=$line
+            fi
+            if [[ $line == *"Failed"* ]]; then
+              echo "::error file=,line=,title=$STR1::$STR2"
+            fi
+          done
+          exit 1
+
       - name: Display results
         run: |
           ./ftest/ftest > ftest.log
-          if [[ $? -ne 0 ]]; then
-            IFS=$'\n'
-            STR1=""
-            STR2=""
-            for line in $(cat ftest.log | grep Failed --before-context=2); do
-              if [[ $line != *"Failed"* && $line == *"----"* ]]; then
-                STR1=$line
-              elif [[ $line != *"Failed"* && $line != *"----"* ]]; then
-                STR2=$line
-              fi
-              if [[ $line == *"Failed"* ]]; then
-                echo "::error file=,line=,title=$STR1::$STR2"
-              fi
-            done
-            exit 1
-          else
-            echo "::notice::All ftests passed"
-            success=$(tail -n 1 ftest.log)
-            echo "::notice::$success"
-          fi
-        continue-on-error: true
+          echo "::notice::All ftests passed"
+          success=$(tail -n 1 ftest.log)
+          echo "::notice::$success"
